Add workflow command tests
Signed-off-by: Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -14,3 +14,8 @@ jobs:
         run: echo "${GITHUB_CONTEXT}"
         env:
           GITHUB_CONTEXT: ${{ toJSON(github) }}
+
+      - name: "Test workflow commands"
+        run: |
+          echo "::error::Test 1"
+          echo "::error::Test 2" 1>&2
