Test ordering and grouping
Signed-off-by: Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -19,3 +19,11 @@ jobs:
         run: |
           echo "::error::Test 1"
           echo "::error::Test 2" 1>&2
+          echo "::error::Test 3"
+          echo "::error::Test 4" 1>&2
+          echo "::group::Group"
+          echo "::error::Test 5"
+          echo "::error::Test 6" 1>&2
+          echo "::endGroup::"
+          echo "::error::Test 7"
+          echo "::error::Test 8" 1>&2
