Update debug.yml
Signed-off-by: Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -13,13 +13,29 @@ on:
 
 jobs:
 
-  dubug-json-properties:
+  debug-regex:
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          if [[ "${TAG_NAME}" =~ "${REG_EXPR}" ]]
+          then
+            echo "::debug::Tag name '${TAG_NAME}' looks good!"
+            exit 0
+          else
+            echo "::error title=VALIDATION ERROR::Tag name '${TAG_NAME}' must match regex: '${REG_EXPR}'"
+            exit 1
+          fi
+        env:
+          TAG_NAME: 'rc25.3.2'
+          REG_EXPR: '^rc[1-9][0-9]+?(\.[0-9]+(\.[0-9]+)?)?$'
+
+  debug-json-properties:
     name: "Dubug json properties"
     runs-on: ubuntu-latest
     steps:
       - run: echo "${{ fromJSON('[{}, {}]') }}"
 
-  dubug-ubuntu-arm:
+  debug-ubuntu-arm:
     name: "Debug ${{ matrix.runner }}"
     runs-on: ${{ matrix.runner }}
 
